
 CREATE TABLE cont_ztrans_utbkmanagedspecific(
    TransID integer,
    Loan1TransType text,
    Loan2TransType text,
    DeedTransType text,
    BKFSPID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utborrowermailaddress(
    TransId integer,
    BorrowerMailSequenceNumber integer,
    BorrowerMailCareOfName text,
    BorrowerMailHouseNumber text,
    BorrowerMailHouseNumberExt text,
    BorrowerMailStreetPreDirectional text,
    BorrowerMailStreetName text,
    BorrowerMailStreetSuffix text,
    BorrowerMailStreetPostDirectional text,
    BorrowerMailBuildingName text,
    BorrowerMailBuildingNumber text,
    BorrowerMailFullStreetAddress text,
    BorrowerMailCity text,
    BorrowerMailState text,
    BorrowerMailZip text,
    BorrowerMailZip4 text,
    OriginalBorrowerMailFullStreetAddress text,
    OriginalBorrowerMailAddressLastline text,
    BorrowerMailAddressStndCode text,
    BorrowerMailAddressMatchCode text,
    BorrowerMailAddressUnitDesignatorCode text,
    BorrowerMailAddressUnitNumber text,
    BorrowerMailAddressCarrierRoute text,
    BorrowerMailAddressFIPSCode text,
    BorrowerMailAddressLatitude real,
    BorrowerMailAddressLongitude real,
    BorrowerMailAddressCensusTractAndBlock text,
    BorrowerMailAddressConfidenceScore integer,
    BorrowerMailAddressCBSACode integer,
    BorrowerMailAddressCBSADivisionCode integer,
    BorrowerMailAddressMatchType integer,
    BorrowerMailAddressDPV text,
    BorrowerMailAddressGeocodeQualityCode text,
    BorrowerMailAddressQualityCode text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utborrowername(
    TransId integer,
    BorrowerFirstMiddleName text,
    BorrowerLastName text,
    BorrowerIndividualFullName text,
    BorrowerNonIndividualName text,
    BorrowerNameSequenceNumber integer,
    BorrowerMailSequenceNumber integer,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utborrowernamedescriptioncode(
    TransId integer,
    BorrowerDescriptionStndCode text,
    BorrowerDescSequenceNumber integer,
    BorrowerNameSequenceNumber integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utbuyermailaddress(
    TransId integer,
    BuyerMailSequenceNumber integer,
    BuyerMailCareOfName text,
    BuyerMailHouseNumber text,
    BuyerMailHouseNumberExt text,
    BuyerMailStreetPreDirectional text,
    BuyerMailStreetName text,
    BuyerMailStreetSuffix text,
    BuyerMailStreetPostDirectional text,
    BuyerMailBuildingName text,
    BuyerMailBuildingNumber text,
    BuyerMailFullStreetAddress text,
    BuyerMailCity text,
    BuyerMailState text,
    BuyerMailZip text,
    BuyerMailZip4 text,
    OriginalBuyerMailFullStreetAddress text,
    OriginalBuyerMailAddressLastline text,
    BuyerMailAddressStndCode text,
    BuyerMailAddressMatchCode text,
    BuyerMailAddressUnitDesignatorCode text,
    BuyerMailAddressUnitNumber text,
    BuyerMailAddressCarrierRoute text,
    BuyerMailAddressFIPSCode text,
    BuyerMailAddressLatitude real,
    BuyerMailAddressLongitude real,
    BuyerMailAddressCensusTractAndBlock text,
    BuyerMailAddressConfidenceScore integer,
    BuyerMailAddressCBSACode integer,
    BuyerMailAddressCBSADivisionCode integer,
    BuyerMailAddressMatchType integer,
    BuyerMailAddressDPV text,
    BuyerMailAddressGeocodeQualityCode text,
    BuyerMailAddressQualityCode text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utbuyername(
    TransId integer,
    BuyerFirstMiddleName text,
    BuyerLastName text,
    BuyerIndividualFullName text,
    BuyerNonIndividualName text,
    BuyerNameSequenceNumber integer,
    BuyerMailSequenceNumber integer,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utbuyernamedescriptioncode(
    TransId integer,
    BuyerDescriptionStndCode text,
    BuyerDescSequenceNumber integer,
    BuyerNameSequenceNumber integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utdelete(
    FIPS text,
    BatchID integer,
    TransID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utforeclosurenodnosdoc(
    TransId integer,
    OrigNODNOSRecSequenceNumber integer,
    OrigNODNOSRecordingDate text,
    OrigNODNOSDocumentDate text,
    OrigNODNOSDocumentNumber text,
    OrigNODNOSBookNumber text,
    OrigNODNOSPageNumber text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utforeclosurenameaddress(
    TransId integer,
    FCNameAddressSequenceNumber integer,
    FCMailFirstMiddleName text,
    FCMailLastName text,
    FCMailIndividualFullName text,
    FCMailNonIndividualName text,
    FCMailCareOf text,
    FCMailFullStreetAddress text,
    FCMailBuildingName text,
    FCMailBuildingNumber text,
    FCMailUnitDesignator text,
    FCMailUnit text,
    FCMailCity text,
    FCMailState text,
    FCMailZip text,
    FCMailZip4 text,
    FCTelephoneNumber text,
    FCNameAddressStndCode text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utforeclosureoriginalloan(
    TransId integer,
    FCOrigLoanSequenceNumber integer,
    FCOrigLoanRecordingDate text,
    FCOrigLoanDocumentDate text,
    FCOrigLoanDocumentNumber text,
    FCOrigLoanBookNumber text,
    FCOrigLoanPageNumber text,
    FCOrigLender text,
    FCOrigLenderTypeStndCode text,
    FCOrigLenderIDStndCode text,
    FCOrigLoanAmount real,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_uthawaiiborrowernotes(
    TransID integer,
    BorrowerNotesSequenceNumber integer,
    HawaiiBorrowerNotesStndCode text,
    HawaiiBorrowerNotes text,
    LoadID integer,
    BorrowerNameSequenceNumber integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_uthawaiigranteenotes(
    TransID integer,
    GranteeNotesSequenceNumber integer,
    HawaiiGranteeNotesStndCode text,
    HawaiiGranteeNotes text,
    LoadID integer,
    GranteeNameSequenceNumber integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utlegacy(
    TransID integer,
    SecondMtgLoanAmount real,
    SecondMtgeLenderTypeStndCode text,
    WAExciseTaxNumber text,
    TNPreviousDocumentNumber text,
    TNPreviousPageNumber text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utmain(
    TransId integer,
    FIPS text,
    State text,
    County text,
    DataClassStndCode text,
    RecordTypeStndCode text,
    RecordingDate text,
    RecordingDocumentNumber text,
    RecordingBookNumber text,
    RecordingPageNumber text,
    ReRecordedCorrectionStndCode text,
    PriorRecordingDate text,
    PriorDocumentDate text,
    PriorDocumentNumber text,
    PriorBookNumber text,
    PriorPageNumber text,
    DocumentTypeStndCode text,
    DocumentDate text,
    SignatureDate text,
    EffectiveDate text,
    BuyerVestingStndCode text,
    BuyerMultiVestingFlag text,
    PartialInterestTransferStndCode text,
    PartialInterestTransferPercent real,
    SalesPriceAmount real,
    SalesPriceAmountStndCode text,
    CityTransferTax real,
    CountyTransferTax real,
    StateTransferTax real,
    TotalTransferTax real,
    IntraFamilyTransferFlag text,
    TransferTaxExemptFlag text,
    PropertyUseStndCode text,
    AssessmentLandUseStndCode text,
    OccupancyStatusStndCode text,
    LegalStndCode text,
    BorrowerVestingStndCode text,
    LenderName text,
    LenderTypeStndCode text,
    LenderIDStndCode text,
    LenderDBAName text,
    DBALenderTypeStndCode text,
    DBALenderIDStndCode text,
    LenderMailCareOfName text,
    LenderMailHouseNumber text,
    LenderMailHouseNumberExt text,
    LenderMailStreetPreDirectional text,
    LenderMailStreetName text,
    LenderMailStreetSuffix text,
    LenderMailStreetPostDirectional text,
    LenderMailFullStreetAddress text,
    LenderMailBuildingName text,
    LenderMailBuildingNumber text,
    LenderMailUnitDesignator text,
    LenderMailUnit text,
    LenderMailCity text,
    LenderMailState text,
    LenderMailZip text,
    LenderMailZip4 text,
    LoanAmount real,
    LoanAmountStndCode text,
    MaximumLoanAmount real,
    LoanTypeStndCode text,
    LoanTypeClosedOpenEndStndCode text,
    LoanTypeFutureAdvanceFlag text,
    LoanTypeProgramStndCode text,
    LoanRateTypeStndCode text,
    LoanDueDate text,
    LoanTermMonths integer,
    LoanTermYears integer,
    InitialInterestRate real,
    ARMFirstAdjustmentDate text,
    ARMFirstAdjustmentMaxRate real,
    ARMFirstAdjustmentMinRate real,
    ARMIndexStndCode text,
    ARMAdjustmentFrequencyStndCode text,
    ARMMargin real,
    ARMInitialCap real,
    ARMPeriodicCap real,
    ARMLifetimeCap real,
    ARMMaxInterestRate real,
    ARMMinInterestRate real,
    InterestOnlyFlag text,
    InterestOnlyTerm text,
    PrepaymentPenaltyFlag text,
    PrepaymentPenaltyTerm text,
    BiWeeklyPaymentFlag text,
    AssumabilityRiderFlag text,
    BalloonRiderFlag text,
    CondominiumRiderFlag text,
    PlannedUnitDevelopmentRiderFlag text,
    SecondHomeRiderFlag text,
    OneToFourFamilyRiderFlag text,
    ConcurrentMtgeDocOrBkPg text,
    LoanNumber text,
    MERSMINNumber text,
    CaseNumber text,
    MERSFlag text,
    TitleCompanyName text,
    TitleCompanyIDStndCode text,
    AccommodationRecordingFlag text,
    UnpaidBalance real,
    InstallmentAmount real,
    InstallmentDueDate text,
    TotalDelinquentAmount real,
    DelinquentAsOfDate text,
    CurrentLender text,
    CurrentLenderTypeStndCode text,
    CurrentLenderIDStndCode text,
    TrusteeSaleNumber text,
    AttorneyFileNumber text,
    AuctionDate text,
    AuctionTime time,
    AuctionFullStreetAddress text,
    AuctionCityName text,
    StartingBid real,
    KeyedDate text,
    KeyerID text,
    SubVendorStndCode text,
    ImageFileName text,
    BuilderFlag text,
    MatchStndCode text,
    REOStndCode text,
    UpdateOwnershipFlag text,
    LoadID integer,
    StatusInd integer,
    TransactionTypeStndCode text,
    BatchID integer,
    BKFSPID integer,
    ZVendorStndCode text,
    SourceChkSum integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utmodification(
    TransId integer,
    ModLoanSequenceNumber integer,
    OrigLoanRecordingDate text,
    LastModRecordingDate text,
    OrigLoanDocumentDate text,
    LastModDocumentDate text,
    OrigLoanORLastModDocumentNumber text,
    OrigLoanORLastModBookNumber text,
    OrigLoanORLastModPageNumber text,
    OrigLoanORLastModLoanAmount real,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utpropertyinfo(
    TransId integer,
    AssessorParcelNumber text,
    APNIndicatorStndCode text,
    TaxIDNumber text,
    TaxIDIndicatorStndCode text,
    UnformattedAssessorParcelNumber text,
    AlternateParcelNumber text,
    HawaiiCondoCPRCode text,
    PropertyHouseNumber text,
    PropertyHouseNumberExt text,
    PropertyStreetPreDirectional text,
    PropertyStreetName text,
    PropertyStreetSuffix text,
    PropertyStreetPostDirectional text,
    PropertyBuildingNumber text,
    PropertyFullStreetAddress text,
    PropertyCity text,
    PropertyState text,
    PropertyZip text,
    PropertyZip4 text,
    OriginalPropertyFullStreetAddress text,
    OriginalPropertyAddressLastline text,
    PropertyAddressStndCode text,
    LegalLot text,
    LegalOtherLot text,
    LegalLotCode text,
    LegalBlock text,
    LegalSubdivisionName text,
    LegalCondoProjectPUDDevName text,
    LegalBuildingNumber text,
    LegalUnit text,
    LegalSection text,
    LegalPhase text,
    LegalTract text,
    LegalDistrict text,
    LegalMunicipality text,
    LegalCity text,
    LegalTownship text,
    LegalSTRSection text,
    LegalSTRTownship text,
    LegalSTRRange text,
    LegalSTRMeridian text,
    LegalSecTwnRngMer text,
    LegalRecordersMapReference text,
    LegalDescription text,
    LegalLotSize text,
    PropertySequenceNumber integer,
    PropertyAddressMatchcode text,
    PropertyAddressUnitDesignator text,
    PropertyAddressUnitNumber text,
    PropertyAddressCarrierRoute text,
    PropertyAddressGeoCodeMatchCode text,
    PropertyAddressLatitude real,
    PropertyAddressLongitude real,
    PropertyAddressCensusTractAndBlock text,
    PropertyAddressConfidenceScore integer,
    PropertyAddressCBSACode integer,
    PropertyAddressCBSADivisionCode integer,
    PropertyAddressMatchType integer,
    PropertyAddressDPV text,
    PropertyGeocodeQualityCode text,
    PropertyAddressQualityCode text,
    FIPS text,
    LoadID integer,
    ImportParcelID integer,
    BKFSPID integer,
    AssessmentRecordMatchFlag integer,
    BatchID integer,
    geom blob,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utregionspecific(
    TransID integer,
    RecordingDistrict text,
    DualSystemRecordingStndCode text,
    DualSystemRecordingDate text,
    DualSystemDocumentNumber text,
    DualSystemBookNumber text,
    DualSystemPageNumber text,
    HawaiiPreviousDualSystemRecStndCode text,
    HawaiiPreviousDualSystemDocNumber text,
    TransferCertificateofTitleNumber text,
    HawaiiTransferTaxRate text,
    LegalHawaiiLandCourtAppNo text,
    LegalHawaiiLandCourtMapNo text,
    LegalHawaiiLandCourtConsolidationNo text,
    LegalHawaiiRegularSystemFilePlanNo text,
    SaleResultsOrStatusStndCode text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utsellermailaddress(
    TransId integer,
    SellerMailSequenceNumber integer,
    SellerMailAddressStndCode text,
    SellerMailCareOfName text,
    SellerMailHouseNumber text,
    SellerMailHouseNumberExt text,
    SellerMailStreetPreDirectional text,
    SellerMailStreetName text,
    SellerMailStreetSuffix text,
    SellerMailStreetPostDirectional text,
    SellerMailBuildingName text,
    SellerMailBuildingNumber text,
    SellerMailFullStreetAddress text,
    SellerMailCity text,
    SellerMailState text,
    SellerMailZip text,
    SellerMailZip4 text,
    OriginalSellerMailFullStreetAddress text,
    OriginalSellerMailAddressLastline text,
    SellerMailAddressMatchCode text,
    SellerMailAddressUnitDesignatorCode text,
    SellerMailAddressUnitNumber text,
    SellerMailAddressCarrierRoute text,
    SellerMailAddressFIPSCode text,
    SellerMailAddressLatitude real,
    SellerMailAddressLongitude real,
    SellerMailAddressCensusTractAndBlock text,
    SellerMailAddressConfidenceScore integer,
    SellerMailAddressCBSACode integer,
    SellerMailAddressCBSADivisionCode integer,
    SellerMailAddressMatchType integer,
    SellerMailAddressDPV text,
    SellerMailAddressGeocodeQualityCode text,
    SellerMailAddressQualityCode text,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utsellername(
    TransId integer,
    SellerFirstMiddleName text,
    SellerLastName text,
    SellerIndividualFullName text,
    SellerNonIndividualName text,
    SellerNameSequenceNumber integer,
    SellerMailSequenceNumber integer,
    LoadID integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_ztrans_utsellernamedescriptioncode(
    TransId integer,
    SellerDescriptionStndCode text,
    SellerDescSequenceNumber integer,
    SellerNameSequenceNumber integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);