
 CREATE TABLE cont_zasmt_utadditionalpropertyaddress(
    RowID text,
    PropertyAddressSequenceNumber integer,
    PropertyHouseNumber text,
    PropertyHouseNumberExt text,
    PropertyStreetPreDirectional text,
    PropertyStreetName text,
    PropertyStreetSuffix text,
    PropertyStreetPostDirectional text,
    PropertyBuildingNumber text,
    PropertyFullStreetAddress text,
    PropertyCity text,
    PropertyState text,
    PropertyZip text,
    PropertyZip4 text,
    OriginalPropertyFullStreetAddress text,
    OriginalPropertyAddressLastline text,
    PropertyAddressCensusTract text,
    PropertyAddressMatchcode text,
    PropertyAddressUnitDesignator text,
    PropertyAddressUnitNumber text,
    PropertyAddressCarrierRoute text,
    PropertyAddressGeoCodeMatchCode text,
    PropertyAddressLatitude real,
    PropertyAddressLongitude real,
    PropertyAddressCensusTractAndBlock text,
    PropertyAddressConfidenceScore integer,
    PropertyAddressCBSACode integer,
    PropertyAddressCBSADivisionCode integer,
    PropertyAddressMatchType integer,
    PropertyAddressDPV text,
    PropertyGeocodeQualityCode text,
    PropertyAddressQualityCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utbkmanagedspecific(
    RowID text,
    LotSizeUnit text,
    LotSizeorArea text,
    BKFSPID integer,
    BKFSLoadDate text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utbuilding(
    RowID text,
    NoOfUnits integer,
    OccupancyStatusStndCode text,
    PropertyCountyLandUseDescription text,
    PropertyCountyLandUseCode text,
    PropertyLandUseStndCode text,
    PropertyStateLandUseDescription text,
    PropertyStateLandUseCode text,
    BuildingOrImprovementNumber integer,
    BuildingClassStndCode text,
    BuildingQualityStndCode text,
    BuildingQualityStndCodeOriginal text,
    BuildingConditionStndCode text,
    ArchitecturalStyleStndCode text,
    YearBuilt integer,
    EffectiveYearBuilt integer,
    YearRemodeled integer,
    NoOfStories text,
    TotalRooms integer,
    TotalBedrooms integer,
    TotalKitchens integer,
    FullBath integer,
    ThreeQuarterBath real,
    HalfBath real,
    QuarterBath real,
    TotalCalculatedBathCount real,
    TotalActualBathCount real,
    BathSourceStndCode text,
    TotalBathPlumbingFixtures integer,
    RoofCoverStndCode text,
    RoofStructureTypeStndCode text,
    HeatingTypeorSystemStndCode text,
    AirConditioningTypeorSystemStndCode text,
    FoundationTypeStndCode text,
    ElevatorStndCode text,
    FireplaceFlag text,
    FirePlaceTypeStndCode text,
    FireplaceNumber integer,
    WaterStndCode text,
    SewerStndCode text,
    MortgageLenderName text,
    TimeshareStndCode text,
    Comments text,
    LoadID integer,
    StoryTypeStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utbuildingareas(
    RowID text,
    BuildingOrImprovementNumber integer,
    BuildingAreaSequenceNumber integer,
    BuildingAreaStndCode text,
    BuildingAreaSqFt integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utcareofname(
    RowID text,
    NameSequenceNumber integer,
    NameTypeStndCode text,
    MailCareOfName text,
    MailCOPatternStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utdelete(
    FIPS text,
    BatchID integer,
    RowID text,
    Edition integer,
    SubEdition integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utexteriorwall(
    RowID text,
    BuildingOrImprovementNumber integer,
    ExteriorWallStndCode text,
    ExteriorWallPercent real,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utextrafeature(
    RowID text,
    BuildingOrImprovementNumber integer,
    ExtraFeatureSequenceNumber integer,
    ExtraFeaturesStndCode text,
    ExtraFeaturesSqFt integer,
    ExtraFeaturesLinearFt integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utgarage(
    RowID text,
    BuildingOrImprovementNumber integer,
    GarageSequenceNumber integer,
    GarageStndCode text,
    GarageAreaSqFt integer,
    GarageNoOfCars integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utinteriorflooring(
    RowID text,
    BuildingOrImprovementNumber integer,
    InteriorFlooringTypeStndCode text,
    FlooringPercent real,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utinteriorwall(
    RowID text,
    BuildingOrImprovementNumber integer,
    InteriorWallStndCode text,
    InteriorWallPercent real,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utlotsiteappeal(
    RowID text,
    LotSiteAppealStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utmailaddress(
    RowID text,
    MailAddressTypeStndCode text,
    MailHouseNumber text,
    MailHouseNumberExt text,
    MailStreetPreDirectional text,
    MailStreetName text,
    MailStreetSuffix text,
    MailStreetPostDirectional text,
    MailBuildingName text,
    MailBuildingNumber text,
    MailFullStreetAddress text,
    MailCity text,
    MailState text,
    MailZip text,
    MailZip4 text,
    OriginalMailFullStreetAddress text,
    OriginalMailAddressLastline text,
    MailCityStateZip text,
    MailInternationalAddressFlag text,
    NameTypeStndCode text,
    MailAddressMatchCode text,
    MailAddressUnitDesignatorCode text,
    MailAddressUnitNumber text,
    MailAddressCarrierRoute text,
    MailAddressFIPSCode text,
    MailAddressLatitude real,
    MailAddressLongitude real,
    MailAddressCensusTractAndBlock text,
    MailAddressConfidenceScore integer,
    MailAddressCBSACode integer,
    MailAddressCBSADivisionCode integer,
    MailAddressMatchType integer,
    MailAddressDPV text,
    MailAddressGeocodeQualityCode text,
    MailAddressQualityCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utmain(
    RowID text,
    ImportParcelID integer,
    FIPS text,
    State text,
    County text,
    ValueCertDate text,
    ExtractDate text,
    Edition integer,
    ZVendorStndCode text,
    AssessorParcelNumber text,
    DupAPN text,
    UnformattedAssessorParcelNumber text,
    ParcelSequenceNumber integer,
    AlternateParcelNumber text,
    OldParcelNumber text,
    ParcelNumberTypeStndCode text,
    RecordSourceStndCode text,
    RecordTypeStndCode text,
    ConfidentialRecordFlag text,
    PropertyAddressSourceStndCode text,
    PropertyHouseNumber text,
    PropertyHouseNumberExt text,
    PropertyStreetPreDirectional text,
    PropertyStreetName text,
    PropertyStreetSuffix text,
    PropertyStreetPostDirectional text,
    PropertyFullStreetAddress text,
    PropertyCity text,
    PropertyState text,
    PropertyZip text,
    PropertyZip4 text,
    OriginalPropertyFullStreetAddress text,
    OriginalPropertyAddressLastline text,
    PropertyBuildingNumber text,
    PropertyZoningDescription text,
    PropertyZoningSourceCode text,
    CensusTract text,
    TaxIDNumber text,
    TaxAmount real,
    TaxYear integer,
    TaxDelinquencyFlag text,
    TaxDelinquencyAmount real,
    TaxDelinquencyYear integer,
    TaxRateCodeArea text,
    LegalLot text,
    LegalLotStndCode text,
    LegalOtherLot text,
    LegalBlock text,
    LegalSubdivisionCode text,
    LegalSubdivisionName text,
    LegalCondoProjectPUDDevName text,
    LegalBuildingNumber text,
    LegalUnit text,
    LegalSection text,
    LegalPhase text,
    LegalTract text,
    LegalDistrict text,
    LegalMunicipality text,
    LegalCity text,
    LegalTownship text,
    LegalSTRSection text,
    LegalSTRTownship text,
    LegalSTRRange text,
    LegalSTRMeridian text,
    LegalSecTwnRngMer text,
    LegalRecordersMapReference text,
    LegalDescription text,
    LegalNeighborhoodSourceCode text,
    NoOfBuildings integer,
    LotSizeAcres real,
    LotSizeSquareFeet real,
    LotSizeFrontageFeet real,
    LotSizeDepthFeet real,
    LotSizeIRR text,
    LotSiteTopographyStndCode text,
    LoadID integer,
    PropertyAddressMatchcode text,
    PropertyAddressUnitDesignator text,
    PropertyAddressUnitNumber text,
    PropertyAddressCarrierRoute text,
    PropertyAddressGeoCodeMatchCode text,
    PropertyAddressLatitude real,
    PropertyAddressLongitude real,
    PropertyAddressCensusTractAndBlock text,
    PropertyAddressConfidenceScore integer,
    PropertyAddressCBSACode integer,
    PropertyAddressCBSADivisionCode integer,
    PropertyAddressMatchType integer,
    PropertyAddressDPV text,
    PropertyGeocodeQualityCode text,
    PropertyAddressQualityCode text,
    SubEdition integer,
    BatchID integer,
    BKFSPID integer,
    SourceChkSum integer,
    geom blob,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utname(
    RowID text,
    Name text,
    NameETStndCode text,
    NameDescriptionStndCode text,
    NameSequenceNumber integer,
    NameTypeStndCode text,
    NamePatternStndCode text,
    NameClassStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utoby(
    RowID text,
    BuildingOrImprovementNumber integer,
    OBYSequenceNumber integer,
    OBYStndCode text,
    OBYAreaSqFt integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utpool(
    RowID text,
    BuildingOrImprovementNumber integer,
    PoolStndCode text,
    PoolSize text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utsaledata(
    RowID text,
    SaleSeqNum integer,
    SellerFullName text,
    BuyerFullName text,
    RecordingDate text,
    DocumentDate text,
    RecordingDocumentNumber text,
    RecordingBookNumber text,
    RecordingPageNumber text,
    DocumentTypeCountyDescription text,
    DocumentTypeStndCode text,
    SalesPriceAmount real,
    SalesPriceAmountStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_uttaxdistrict(
    RowID text,
    TaxDistrictStndCode text,
    TaxDistrictName text,
    TaxDistrictAmount real,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_uttaxexemption(
    RowID text,
    TaxExemptionStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_uttypeconstruction(
    RowID text,
    BuildingOrImprovementNumber integer,
    TypeConstructionStndCode text,
    TypeConstructionPercent real,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utvalue(
    RowID text,
    LandAssessedValue real,
    ImprovementAssessedValue real,
    TotalAssessedValue real,
    AssessmentYear integer,
    LandMarketValue real,
    ImprovementMarketValue real,
    TotalMarketValue real,
    MarketValueYear integer,
    LandAppraisalValue real,
    ImprovementAppraisalValue real,
    TotalAppraisalValue real,
    AppraisalValueYear integer,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);
 CREATE TABLE cont_zasmt_utvestingcodes(
    RowID text,
    NameSequenceNumber integer,
    NameTypeStndCode text,
    OwnerVestingStndCode text,
    FIPS text,
    BatchID integer,
    fme_id text PRIMARY KEY
);